Add cluster_name property to avoid several clusters merging accidentally
quickwit-oss/scuttlebutt pull request #36
Opened 2022-04-07 14:01 UTC by xvello

As described in https://github.com/quickwit-oss/quickwit/pull/1260, we need a mechanism to ensure clusters do not accidentally merge when IPs are reused.

This PR:

- introduces a required `cluster_name` argument when setting up the cluster
- adds that cluster name to outgoing `Syn` messages
- adds a `BadCluster` message type
- if the cluster name in the `Syn` message does not match the peer's cluster name, a `BadCluster` message is returned instead of a `SynAck`

## Additional notes

- This PR changes the wire format, but I did not see any versioning mechanism in the protocol. We should merge this before v0.3 is released, to sidestep any compatibility issue.

2022-04-08 01:28 UTC, fulmicoton requested changes
As you suggested in the PR description, could you add an error message to the protocol?

As you mentioned it is nicer for testing, but also,I suspect a common problem that will occur is a misconfigured typo in the conf of one of the server. The user will likely investigate the log of the server that cannot connect to the cluster first and an explicit error message there might be nice.

2022-04-08 01:44 UTC, fulmicoton commented
I create #37 and #38 too.

2022-04-08 12:22 UTC, xvello commented
I just pushed a commit introducing a `BadCluster` message, instead of silently dropping the message.

I started writing the code with a more generic `Rst` message, but I could not get a relevant error displayed on the misconfigured node without extending it with a `RstReason` enum, which added unneeded complexity.

2022-04-08 13:25 UTC, xvello commented
`ignore_oversized_payload` is failing, but I think this test has lost its initial meaning and is not useful anymore. Discussing it on discord.

2022-04-12 02:11 UTC, fulmicoton commented on scuttlebutt/src/lib.rs
> +                        cluster_name = ?cluster_name,
%

2022-04-12 02:11 UTC, fulmicoton commented on scuttlebutt/src/lib.rs
> +                        cluster_name = ?cluster_name,
```suggestion
                        cluster_name = %cluster_name,
```

2022-04-12 02:13 UTC, fulmicoton approved these changes

2022-04-12 02:18 UTC, fulmicoton commented
@xvello FYI: in tracing ?val will use Debug. %val will call Display.
For a String you want %val 

Alternatively, you can also try to get a &str and avoid any modifier. `key=val.as_str()`

2022-04-12 02:24 UTC, merged